
package eu.aniketos.ncvm.pvm.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-20T15:45:19.765Z
 * Generated source version: 2.7.4
 * 
 */
public final class PropertyVerificationServicePortType_PropertyVerificationServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://propertyverification.verification.components.aniketos.eu/", "PropertyVerificationService");

    private PropertyVerificationServicePortType_PropertyVerificationServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PropertyVerificationServiceClient.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PropertyVerificationServiceClient ss = new PropertyVerificationServiceClient(wsdlURL, SERVICE_NAME);
        PropertyVerificationServicePortType port = ss.getPropertyVerificationServicePort();  
        
        {
        System.out.println("Invoking verifyTechnicalTrustProperties...");
        java.lang.String _verifyTechnicalTrustProperties_arg0 = "";
        java.lang.String _verifyTechnicalTrustProperties_arg1 = "";
        eu.aniketos.ncvm.pvm.client.PropertyVerificationResult _verifyTechnicalTrustProperties__return = port.verifyTechnicalTrustProperties(_verifyTechnicalTrustProperties_arg0, _verifyTechnicalTrustProperties_arg1);
        System.out.println("verifyTechnicalTrustProperties.result=" + _verifyTechnicalTrustProperties__return);


        }
        {
        System.out.println("Invoking verifyWSDL...");
        java.lang.String _verifyWSDL_arg0 = "";
        java.lang.String _verifyWSDL_arg1 = "";
        java.lang.String _verifyWSDL_arg2 = "";
        int _verifyWSDL_arg3 = 0;
        java.lang.String _verifyWSDL_arg4 = "";
        java.lang.String _verifyWSDL_arg5 = "";
        java.lang.String _verifyWSDL_arg6 = "";
        int _verifyWSDL_arg7 = 0;
        java.lang.String _verifyWSDL_arg8 = "";
        eu.aniketos.ncvm.pvm.client.PropertyVerificationResult _verifyWSDL__return = port.verifyWSDL(_verifyWSDL_arg0, _verifyWSDL_arg1, _verifyWSDL_arg2, _verifyWSDL_arg3, _verifyWSDL_arg4, _verifyWSDL_arg5, _verifyWSDL_arg6, _verifyWSDL_arg7, _verifyWSDL_arg8);
        System.out.println("verifyWSDL.result=" + _verifyWSDL__return);


        }

        System.exit(0);
    }

}
