
package eu.aniketos.ncvm.marketplace.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-04-01T03:54:58.326+01:00
 * Generated source version: 2.7.10
 * 
 */
public final class IMarketplacePortType_IMarketplacePort_Client {

    private static final QName SERVICE_NAME = new QName("http://marketplace.aniketos.eu/", "IMarketplace");

    private IMarketplacePortType_IMarketplacePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IMarketplaceClient.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IMarketplaceClient ss = new IMarketplaceClient(wsdlURL, SERVICE_NAME);
        IMarketplacePortType port = ss.getIMarketplacePort();  
        
        {
        System.out.println("Invoking getRules...");
        java.lang.String _getRules_arg0 = "";
        java.lang.String _getRules__return = port.getRules(_getRules_arg0);
        System.out.println("getRules.result=" + _getRules__return);


        }
        {
        System.out.println("Invoking notProvide...");
        java.lang.String _notProvide_arg0 = "";
        java.lang.String _notProvide_arg1 = "";
        port.notProvide(_notProvide_arg0, _notProvide_arg1);


        }
        {
        System.out.println("Invoking getSecurityDescriptor...");
        java.lang.String _getSecurityDescriptor_arg0 = "";
        java.lang.String _getSecurityDescriptor_arg1 = "";
        eu.aniketos.ncvm.marketplace.client.MarketplaceSecurityDescriptor _getSecurityDescriptor__return = port.getSecurityDescriptor(_getSecurityDescriptor_arg0, _getSecurityDescriptor_arg1);
        System.out.println("getSecurityDescriptor.result=" + _getSecurityDescriptor__return);


        }
        {
        System.out.println("Invoking provide...");
        java.lang.String _provide_arg0 = "";
        java.lang.String _provide_arg1 = "";
        port.provide(_provide_arg0, _provide_arg1);


        }
        {
        System.out.println("Invoking announceService...");
        java.lang.String _announceService_arg0 = "";
        eu.aniketos.ncvm.marketplace.client.MarketplaceAnnouncement _announceService_arg1 = null;
        java.lang.String _announceService__return = port.announceService(_announceService_arg0, _announceService_arg1);
        System.out.println("announceService.result=" + _announceService__return);


        }
        {
        System.out.println("Invoking getBpmnDiagram...");
        java.lang.String _getBpmnDiagram_arg0 = "";
        java.lang.String _getBpmnDiagram__return = port.getBpmnDiagram(_getBpmnDiagram_arg0);
        System.out.println("getBpmnDiagram.result=" + _getBpmnDiagram__return);


        }
        {
        System.out.println("Invoking deleteService...");
        java.lang.String _deleteService_arg0 = "";
        java.lang.String _deleteService_arg1 = "";
        boolean _deleteService__return = port.deleteService(_deleteService_arg0, _deleteService_arg1);
        System.out.println("deleteService.result=" + _deleteService__return);


        }
        {
        System.out.println("Invoking getAuthToken...");
        java.lang.String _getAuthToken_arg0 = "";
        java.lang.String _getAuthToken_arg1 = "";
        java.lang.String _getAuthToken__return = port.getAuthToken(_getAuthToken_arg0, _getAuthToken_arg1);
        System.out.println("getAuthToken.result=" + _getAuthToken__return);


        }
        {
        System.out.println("Invoking getSource...");
        java.lang.String _getSource_arg0 = "";
        java.lang.String _getSource__return = port.getSource(_getSource_arg0);
        System.out.println("getSource.result=" + _getSource__return);


        }
        {
        System.out.println("Invoking registerSource...");
        java.lang.String _registerSource_arg0 = "";
        java.lang.String _registerSource_arg1 = "";
        boolean _registerSource__return = port.registerSource(_registerSource_arg0, _registerSource_arg1);
        System.out.println("registerSource.result=" + _registerSource__return);


        }
        {
        System.out.println("Invoking getTags...");
        java.lang.String _getTags_arg0 = "";
        eu.aniketos.ncvm.marketplace.client.ArrayOfTag _getTags__return = port.getTags(_getTags_arg0);
        System.out.println("getTags.result=" + _getTags__return);


        }
        {
        System.out.println("Invoking updateSecurityDescription...");
        java.lang.String _updateSecurityDescription_arg0 = "";
        java.lang.String _updateSecurityDescription_arg1 = "";
        eu.aniketos.ncvm.marketplace.client.IConsumerPolicy _updateSecurityDescription_arg2 = null;
        boolean _updateSecurityDescription__return = port.updateSecurityDescription(_updateSecurityDescription_arg0, _updateSecurityDescription_arg1, _updateSecurityDescription_arg2);
        System.out.println("updateSecurityDescription.result=" + _updateSecurityDescription__return);


        }
        {
        System.out.println("Invoking discoverService...");
        java.lang.String _discoverService_arg0 = "";
        eu.aniketos.ncvm.marketplace.client.MarketplaceSearchParams _discoverService_arg1 = null;
        eu.aniketos.ncvm.marketplace.client.ArrayOfServiceDescriptor _discoverService__return = port.discoverService(_discoverService_arg0, _discoverService_arg1);
        System.out.println("discoverService.result=" + _discoverService__return);


        }
        {
        System.out.println("Invoking getCompositionPlans...");
        java.lang.String _getCompositionPlans_arg0 = "";
        eu.aniketos.ncvm.marketplace.client.ArrayOfICompositionPlan _getCompositionPlans__return = port.getCompositionPlans(_getCompositionPlans_arg0);
        System.out.println("getCompositionPlans.result=" + _getCompositionPlans__return);


        }
        {
        System.out.println("Invoking isTestable...");
        java.lang.String _isTestable_arg0 = "";
        boolean _isTestable__return = port.isTestable(_isTestable_arg0);
        System.out.println("isTestable.result=" + _isTestable__return);


        }
        {
        System.out.println("Invoking updateBpmnDiagram...");
        java.lang.String _updateBpmnDiagram_arg0 = "";
        java.lang.String _updateBpmnDiagram_arg1 = "";
        java.lang.String _updateBpmnDiagram_arg2 = "";
        boolean _updateBpmnDiagram__return = port.updateBpmnDiagram(_updateBpmnDiagram_arg0, _updateBpmnDiagram_arg1, _updateBpmnDiagram_arg2);
        System.out.println("updateBpmnDiagram.result=" + _updateBpmnDiagram__return);


        }

        System.exit(0);
    }

}
