package eu.aniketos.ncvm.marketplace.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-04-01T03:54:58.396+01:00
 * Generated source version: 2.7.10
 * 
 */
@WebServiceClient(name = "IMarketplace", 
                  wsdlLocation = "http://hestia.atc.gr/marketplace2?wsdl",
                  targetNamespace = "http://marketplace.aniketos.eu/") 
public class IMarketplaceClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://marketplace.aniketos.eu/", "IMarketplace");
    public final static QName IMarketplacePort = new QName("http://marketplace.aniketos.eu/", "IMarketplacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://hestia.atc.gr/marketplace2?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IMarketplaceClient.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://hestia.atc.gr/marketplace2?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IMarketplaceClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IMarketplaceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMarketplaceClient() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IMarketplacePortType
     */
    @WebEndpoint(name = "IMarketplacePort")
    public IMarketplacePortType getIMarketplacePort() {
        return super.getPort(IMarketplacePort, IMarketplacePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMarketplacePortType
     */
    @WebEndpoint(name = "IMarketplacePort")
    public IMarketplacePortType getIMarketplacePort(WebServiceFeature... features) {
        return super.getPort(IMarketplacePort, IMarketplacePortType.class, features);
    }

}
