package eu.aniketos.ncvm.marketplace.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-04-01T03:54:58.380+01:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://marketplace.aniketos.eu/", name = "IMarketplacePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IMarketplacePortType {

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "getRules", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetRules")
    @WebMethod
    @ResponseWrapper(localName = "getRulesResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetRulesResponse")
    public java.lang.String getRules(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "notProvide", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.NotProvide")
    @WebMethod
    @ResponseWrapper(localName = "notProvideResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.NotProvideResponse")
    public void notProvide(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "getSecurityDescriptor", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetSecurityDescriptor")
    @WebMethod
    @ResponseWrapper(localName = "getSecurityDescriptorResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetSecurityDescriptorResponse")
    public eu.aniketos.ncvm.marketplace.client.MarketplaceSecurityDescriptor getSecurityDescriptor(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "provide", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.Provide")
    @WebMethod
    @ResponseWrapper(localName = "provideResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.ProvideResponse")
    public void provide(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "announceService", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.AnnounceService")
    @WebMethod
    @ResponseWrapper(localName = "announceServiceResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.AnnounceServiceResponse")
    public java.lang.String announceService(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://marketplace.aniketos.eu/")
        eu.aniketos.ncvm.marketplace.client.MarketplaceAnnouncement arg1
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "getBpmnDiagram", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetBpmnDiagram")
    @WebMethod
    @ResponseWrapper(localName = "getBpmnDiagramResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetBpmnDiagramResponse")
    public java.lang.String getBpmnDiagram(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "deleteService", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.DeleteService")
    @WebMethod
    @ResponseWrapper(localName = "deleteServiceResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.DeleteServiceResponse")
    public boolean deleteService(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "getAuthToken", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetAuthToken")
    @WebMethod
    @ResponseWrapper(localName = "getAuthTokenResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetAuthTokenResponse")
    public java.lang.String getAuthToken(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "getSource", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetSource")
    @WebMethod
    @ResponseWrapper(localName = "getSourceResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetSourceResponse")
    public java.lang.String getSource(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "registerSource", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.RegisterSource")
    @WebMethod
    @ResponseWrapper(localName = "registerSourceResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.RegisterSourceResponse")
    public boolean registerSource(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "getTags", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetTags")
    @WebMethod
    @ResponseWrapper(localName = "getTagsResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetTagsResponse")
    public eu.aniketos.ncvm.marketplace.client.ArrayOfTag getTags(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "updateSecurityDescription", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.UpdateSecurityDescription")
    @WebMethod
    @ResponseWrapper(localName = "updateSecurityDescriptionResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.UpdateSecurityDescriptionResponse")
    public boolean updateSecurityDescription(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://marketplace.aniketos.eu/")
        eu.aniketos.ncvm.marketplace.client.IConsumerPolicy arg2
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "discoverService", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.DiscoverService")
    @WebMethod
    @ResponseWrapper(localName = "discoverServiceResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.DiscoverServiceResponse")
    public eu.aniketos.ncvm.marketplace.client.ArrayOfServiceDescriptor discoverService(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://marketplace.aniketos.eu/")
        eu.aniketos.ncvm.marketplace.client.MarketplaceSearchParams arg1
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "getCompositionPlans", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetCompositionPlans")
    @WebMethod
    @ResponseWrapper(localName = "getCompositionPlansResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.GetCompositionPlansResponse")
    public eu.aniketos.ncvm.marketplace.client.ArrayOfICompositionPlan getCompositionPlans(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "isTestable", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.IsTestable")
    @WebMethod
    @ResponseWrapper(localName = "isTestableResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.IsTestableResponse")
    public boolean isTestable(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://marketplace.aniketos.eu/")
    @RequestWrapper(localName = "updateBpmnDiagram", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.UpdateBpmnDiagram")
    @WebMethod
    @ResponseWrapper(localName = "updateBpmnDiagramResponse", targetNamespace = "http://marketplace.aniketos.eu/", className = "eu.aniketos.ncvm.marketplace.client.UpdateBpmnDiagramResponse")
    public boolean updateBpmnDiagram(
        @WebParam(name = "arg0", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://marketplace.aniketos.eu/")
        java.lang.String arg2
    );
}
