package eu.aniketos.ncvm.csvm.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-20T14:15:57.554Z
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "CompositionSecurityValidationService", 
                  wsdlLocation = "http://ec2-54-235-118-152.compute-1.amazonaws.com:9095/csvm?wsdl",
                  targetNamespace = "http://compositionsecurityvalidation.verification.components.aniketos.eu/") 
public class CompositionSecurityValidationServiceClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://compositionsecurityvalidation.verification.components.aniketos.eu/", "CompositionSecurityValidationService");
    public final static QName CompositionSecurityValidationServicePort = new QName("http://compositionsecurityvalidation.verification.components.aniketos.eu/", "CompositionSecurityValidationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://ec2-54-235-118-152.compute-1.amazonaws.com:9095/csvm?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CompositionSecurityValidationServiceClient.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ec2-54-235-118-152.compute-1.amazonaws.com:9095/csvm?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CompositionSecurityValidationServiceClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CompositionSecurityValidationServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompositionSecurityValidationServiceClient() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CompositionSecurityValidationServicePortType
     */
    @WebEndpoint(name = "CompositionSecurityValidationServicePort")
    public CompositionSecurityValidationServicePortType getCompositionSecurityValidationServicePort() {
        return super.getPort(CompositionSecurityValidationServicePort, CompositionSecurityValidationServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompositionSecurityValidationServicePortType
     */
    @WebEndpoint(name = "CompositionSecurityValidationServicePort")
    public CompositionSecurityValidationServicePortType getCompositionSecurityValidationServicePort(WebServiceFeature... features) {
        return super.getPort(CompositionSecurityValidationServicePort, CompositionSecurityValidationServicePortType.class, features);
    }

}
