package eu.aniketos.ncvm.csvm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-20T14:15:57.505Z
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://compositionsecurityvalidation.verification.components.aniketos.eu/", name = "CompositionSecurityValidationServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CompositionSecurityValidationServicePortType {

    @WebResult(name = "return", targetNamespace = "http://compositionsecurityvalidation.verification.components.aniketos.eu/")
    @RequestWrapper(localName = "VerifyCompositionCompliance", targetNamespace = "http://compositionsecurityvalidation.verification.components.aniketos.eu/", className = "eu.aniketos.ncvm.csvm.client.VerifyCompositionCompliance")
    @WebMethod(operationName = "VerifyCompositionCompliance")
    @ResponseWrapper(localName = "VerifyCompositionComplianceResponse", targetNamespace = "http://compositionsecurityvalidation.verification.components.aniketos.eu/", className = "eu.aniketos.ncvm.csvm.client.VerifyCompositionComplianceResponse")
    public eu.aniketos.ncvm.csvm.client.CompositionSecurityValidationResult verifyCompositionCompliance(
        @WebParam(name = "arg0", targetNamespace = "http://compositionsecurityvalidation.verification.components.aniketos.eu/")
        eu.aniketos.ncvm.csvm.client.ICompositionPlan arg0
    );
}
