package eu.aniketos.ncvm.spdm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-20T16:42:07.184Z
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://api.ds.spdm.aniketos.eu/", name = "ISPDMServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ISPDMServicePortType {

    @WebResult(name = "return", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
    @RequestWrapper(localName = "getService", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetService")
    @WebMethod
    @ResponseWrapper(localName = "getServiceResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetServiceResponse")
    public eu.aniketos.ncvm.spdm.client.IWebService getService(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "removeSeucrityProeprty", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.RemoveSeucrityProeprty")
    @WebMethod
    @ResponseWrapper(localName = "removeSeucrityProeprtyResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.RemoveSeucrityProeprtyResponse")
    public void removeSeucrityProeprty(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        eu.aniketos.ncvm.spdm.client.ISecurityProperty arg0
    );

    @RequestWrapper(localName = "emptyCache", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.EmptyCache")
    @WebMethod
    @ResponseWrapper(localName = "emptyCacheResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.EmptyCacheResponse")
    public void emptyCache();

    @WebResult(name = "return", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
    @RequestWrapper(localName = "getSecurityProperty", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetSecurityProperty")
    @WebMethod
    @ResponseWrapper(localName = "getSecurityPropertyResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetSecurityPropertyResponse")
    public eu.aniketos.ncvm.spdm.client.ISecurityProperty getSecurityProperty(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
    @RequestWrapper(localName = "getTestResults", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetTestResults")
    @WebMethod
    @ResponseWrapper(localName = "getTestResultsResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetTestResultsResponse")
    public java.lang.String getTestResults();

    @RequestWrapper(localName = "print_ws_entries", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.PrintWsEntries")
    @WebMethod(operationName = "print_ws_entries")
    @ResponseWrapper(localName = "print_ws_entriesResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.PrintWsEntriesResponse")
    public void printWsEntries();

    @RequestWrapper(localName = "persist_cache", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.PersistCache")
    @WebMethod(operationName = "persist_cache")
    @ResponseWrapper(localName = "persist_cacheResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.PersistCacheResponse")
    public void persistCache();

    @RequestWrapper(localName = "print_repository", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.PrintRepository")
    @WebMethod(operationName = "print_repository")
    @ResponseWrapper(localName = "print_repositoryResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.PrintRepositoryResponse")
    public void printRepository();

    @RequestWrapper(localName = "registerService", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.RegisterService")
    @WebMethod
    @ResponseWrapper(localName = "registerServiceResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.RegisterServiceResponse")
    public void registerService(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        eu.aniketos.ncvm.spdm.client.IWebService arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        eu.aniketos.ncvm.spdm.client.ISecurityDescriptor arg1
    );

    @RequestWrapper(localName = "startTest", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.StartTest")
    @WebMethod
    @ResponseWrapper(localName = "startTestResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.StartTestResponse")
    public void startTest();

    @WebResult(name = "return", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
    @RequestWrapper(localName = "updateSecurityProperty", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.UpdateSecurityProperty")
    @WebMethod
    @ResponseWrapper(localName = "updateSecurityPropertyResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.UpdateSecurityPropertyResponse")
    public int updateSecurityProperty(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
    @RequestWrapper(localName = "getProperties", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetProperties")
    @WebMethod
    @ResponseWrapper(localName = "getPropertiesResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetPropertiesResponse")
    public eu.aniketos.ncvm.spdm.client.ArrayOfISecurityProperty getProperties(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        eu.aniketos.ncvm.spdm.client.IWebService arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        eu.aniketos.ncvm.spdm.client.SPState arg1
    );

    @WebResult(name = "return", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
    @RequestWrapper(localName = "getVerifiedProperties", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetVerifiedProperties")
    @WebMethod
    @ResponseWrapper(localName = "getVerifiedPropertiesResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetVerifiedPropertiesResponse")
    public eu.aniketos.ncvm.spdm.client.ArrayOfISecurityProperty getVerifiedProperties(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        eu.aniketos.ncvm.spdm.client.IWebService arg0
    );

    @WebResult(name = "return", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
    @RequestWrapper(localName = "fetchRepository", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.FetchRepository")
    @WebMethod
    @ResponseWrapper(localName = "fetchRepositoryResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.FetchRepositoryResponse")
    public eu.aniketos.ncvm.spdm.client.ISPSRepository fetchRepository();

    @RequestWrapper(localName = "print_sp_entries", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.PrintSpEntries")
    @WebMethod(operationName = "print_sp_entries")
    @ResponseWrapper(localName = "print_sp_entriesResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.PrintSpEntriesResponse")
    public void printSpEntries();

    @WebResult(name = "return", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
    @RequestWrapper(localName = "lookUpSecurityProperty", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.LookUpSecurityProperty")
    @WebMethod
    @ResponseWrapper(localName = "lookUpSecurityPropertyResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.LookUpSecurityPropertyResponse")
    public eu.aniketos.ncvm.spdm.client.ArrayOfISecurityProperty lookUpSecurityProperty(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        eu.aniketos.ncvm.spdm.client.IWebService arg0
    );

    @RequestWrapper(localName = "unregisterService", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.UnregisterService")
    @WebMethod
    @ResponseWrapper(localName = "unregisterServiceResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.UnregisterServiceResponse")
    public void unregisterService(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        eu.aniketos.ncvm.spdm.client.IWebService arg0
    );

    @RequestWrapper(localName = "registerService1", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.RegisterService1")
    @WebMethod
    @ResponseWrapper(localName = "registerService1Response", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.RegisterService1Response")
    public void registerService1(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        eu.aniketos.ncvm.spdm.client.IWebService arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        eu.aniketos.ncvm.spdm.client.ISecurityProperty arg1
    );

    @RequestWrapper(localName = "setTestResults", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.SetTestResults")
    @WebMethod
    @ResponseWrapper(localName = "setTestResultsResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.SetTestResultsResponse")
    public void setTestResults(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
    @RequestWrapper(localName = "cache_size", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.CacheSize")
    @WebMethod(operationName = "cache_size")
    @ResponseWrapper(localName = "cache_sizeResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.CacheSizeResponse")
    public int cacheSize();

    @WebResult(name = "return", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
    @RequestWrapper(localName = "lookupService", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.LookupService")
    @WebMethod
    @ResponseWrapper(localName = "lookupServiceResponse", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.LookupServiceResponse")
    public eu.aniketos.ncvm.spdm.client.ArrayOfIWebService lookupService(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        eu.aniketos.ncvm.spdm.client.ISecurityProperty arg0
    );

    @WebResult(name = "return", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
    @RequestWrapper(localName = "getSecurityProperty1", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetSecurityProperty1")
    @WebMethod
    @ResponseWrapper(localName = "getSecurityProperty1Response", targetNamespace = "http://api.ds.spdm.aniketos.eu/", className = "eu.aniketos.ncvm.spdm.client.GetSecurityProperty1Response")
    public eu.aniketos.ncvm.spdm.client.ISecurityProperty getSecurityProperty1(
        @WebParam(name = "arg0", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.ds.spdm.aniketos.eu/")
        java.lang.String arg1
    );
}
