package eu.aniketos.ncvm.spdm.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-20T16:42:07.212Z
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "ISPDMService", 
                  wsdlLocation = "http://ec2-54-235-118-152.compute-1.amazonaws.com:9091/spdm_service?wsdl",
                  targetNamespace = "http://api.ds.spdm.aniketos.eu/") 
public class ISPDMServiceClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://api.ds.spdm.aniketos.eu/", "ISPDMService");
    public final static QName ISPDMServicePort = new QName("http://api.ds.spdm.aniketos.eu/", "ISPDMServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://ec2-54-235-118-152.compute-1.amazonaws.com:9091/spdm_service?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ISPDMServiceClient.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ec2-54-235-118-152.compute-1.amazonaws.com:9091/spdm_service?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ISPDMServiceClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ISPDMServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISPDMServiceClient() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ISPDMServicePortType
     */
    @WebEndpoint(name = "ISPDMServicePort")
    public ISPDMServicePortType getISPDMServicePort() {
        return super.getPort(ISPDMServicePort, ISPDMServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISPDMServicePortType
     */
    @WebEndpoint(name = "ISPDMServicePort")
    public ISPDMServicePortType getISPDMServicePort(WebServiceFeature... features) {
        return super.getPort(ISPDMServicePort, ISPDMServicePortType.class, features);
    }

}
