
package eu.aniketos.ncvm.spdm.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-20T16:42:07.073Z
 * Generated source version: 2.7.4
 * 
 */
public final class ISPDMServicePortType_ISPDMServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://api.ds.spdm.aniketos.eu/", "ISPDMService");

    private ISPDMServicePortType_ISPDMServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ISPDMServiceClient.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ISPDMServiceClient ss = new ISPDMServiceClient(wsdlURL, SERVICE_NAME);
        ISPDMServicePortType port = ss.getISPDMServicePort();  
        
        {
        System.out.println("Invoking getService...");
        java.lang.String _getService_arg0 = "";
        eu.aniketos.ncvm.spdm.client.IWebService _getService__return = port.getService(_getService_arg0);
        System.out.println("getService.result=" + _getService__return);


        }
        {
        System.out.println("Invoking removeSeucrityProeprty...");
        eu.aniketos.ncvm.spdm.client.ISecurityProperty _removeSeucrityProeprty_arg0 = null;
        port.removeSeucrityProeprty(_removeSeucrityProeprty_arg0);


        }
        {
        System.out.println("Invoking emptyCache...");
        port.emptyCache();


        }
        {
        System.out.println("Invoking getSecurityProperty...");
        java.lang.String _getSecurityProperty_arg0 = "";
        eu.aniketos.ncvm.spdm.client.ISecurityProperty _getSecurityProperty__return = port.getSecurityProperty(_getSecurityProperty_arg0);
        System.out.println("getSecurityProperty.result=" + _getSecurityProperty__return);


        }
        {
        System.out.println("Invoking getTestResults...");
        java.lang.String _getTestResults__return = port.getTestResults();
        System.out.println("getTestResults.result=" + _getTestResults__return);


        }
        {
        System.out.println("Invoking printWsEntries...");
        port.printWsEntries();


        }
        {
        System.out.println("Invoking persistCache...");
        port.persistCache();


        }
        {
        System.out.println("Invoking printRepository...");
        port.printRepository();


        }
        {
        System.out.println("Invoking registerService...");
        eu.aniketos.ncvm.spdm.client.IWebService _registerService_arg0 = null;
        eu.aniketos.ncvm.spdm.client.ISecurityDescriptor _registerService_arg1 = null;
        port.registerService(_registerService_arg0, _registerService_arg1);


        }
        {
        System.out.println("Invoking startTest...");
        port.startTest();


        }
        {
        System.out.println("Invoking updateSecurityProperty...");
        java.lang.String _updateSecurityProperty_arg0 = "";
        java.lang.String _updateSecurityProperty_arg1 = "";
        java.lang.String _updateSecurityProperty_arg2 = "";
        int _updateSecurityProperty__return = port.updateSecurityProperty(_updateSecurityProperty_arg0, _updateSecurityProperty_arg1, _updateSecurityProperty_arg2);
        System.out.println("updateSecurityProperty.result=" + _updateSecurityProperty__return);


        }
        {
        System.out.println("Invoking getProperties...");
        eu.aniketos.ncvm.spdm.client.IWebService _getProperties_arg0 = null;
        eu.aniketos.ncvm.spdm.client.SPState _getProperties_arg1 = null;
        eu.aniketos.ncvm.spdm.client.ArrayOfISecurityProperty _getProperties__return = port.getProperties(_getProperties_arg0, _getProperties_arg1);
        System.out.println("getProperties.result=" + _getProperties__return);


        }
        {
        System.out.println("Invoking getVerifiedProperties...");
        eu.aniketos.ncvm.spdm.client.IWebService _getVerifiedProperties_arg0 = null;
        eu.aniketos.ncvm.spdm.client.ArrayOfISecurityProperty _getVerifiedProperties__return = port.getVerifiedProperties(_getVerifiedProperties_arg0);
        System.out.println("getVerifiedProperties.result=" + _getVerifiedProperties__return);


        }
        {
        System.out.println("Invoking fetchRepository...");
        eu.aniketos.ncvm.spdm.client.ISPSRepository _fetchRepository__return = port.fetchRepository();
        System.out.println("fetchRepository.result=" + _fetchRepository__return);


        }
        {
        System.out.println("Invoking printSpEntries...");
        port.printSpEntries();


        }
        {
        System.out.println("Invoking lookUpSecurityProperty...");
        eu.aniketos.ncvm.spdm.client.IWebService _lookUpSecurityProperty_arg0 = null;
        eu.aniketos.ncvm.spdm.client.ArrayOfISecurityProperty _lookUpSecurityProperty__return = port.lookUpSecurityProperty(_lookUpSecurityProperty_arg0);
        System.out.println("lookUpSecurityProperty.result=" + _lookUpSecurityProperty__return);


        }
        {
        System.out.println("Invoking unregisterService...");
        eu.aniketos.ncvm.spdm.client.IWebService _unregisterService_arg0 = null;
        port.unregisterService(_unregisterService_arg0);


        }
        {
        System.out.println("Invoking registerService1...");
        eu.aniketos.ncvm.spdm.client.IWebService _registerService1_arg0 = null;
        eu.aniketos.ncvm.spdm.client.ISecurityProperty _registerService1_arg1 = null;
        port.registerService1(_registerService1_arg0, _registerService1_arg1);


        }
        {
        System.out.println("Invoking setTestResults...");
        java.lang.String _setTestResults_arg0 = "";
        port.setTestResults(_setTestResults_arg0);


        }
        {
        System.out.println("Invoking cacheSize...");
        int _cacheSize__return = port.cacheSize();
        System.out.println("cacheSize.result=" + _cacheSize__return);


        }
        {
        System.out.println("Invoking lookupService...");
        eu.aniketos.ncvm.spdm.client.ISecurityProperty _lookupService_arg0 = null;
        eu.aniketos.ncvm.spdm.client.ArrayOfIWebService _lookupService__return = port.lookupService(_lookupService_arg0);
        System.out.println("lookupService.result=" + _lookupService__return);


        }
        {
        System.out.println("Invoking getSecurityProperty1...");
        java.lang.String _getSecurityProperty1_arg0 = "";
        java.lang.String _getSecurityProperty1_arg1 = "";
        eu.aniketos.ncvm.spdm.client.ISecurityProperty _getSecurityProperty1__return = port.getSecurityProperty1(_getSecurityProperty1_arg0, _getSecurityProperty1_arg1);
        System.out.println("getSecurityProperty1.result=" + _getSecurityProperty1__return);


        }

        System.exit(0);
    }

}
