package eu.aniketos.ncvm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-27T00:54:55.013Z
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://ncvm.aniketos.eu/", name = "INestedCompositionVerificationPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface INestedCompositionVerificationPortType {

    @RequestWrapper(localName = "performTests", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.PerformTests")
    @WebMethod
    @ResponseWrapper(localName = "performTestsResponse", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.PerformTestsResponse")
    public void performTests();

    @WebResult(name = "return", targetNamespace = "http://ncvm.aniketos.eu/")
    @RequestWrapper(localName = "verifyProperty", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.VerifyProperty")
    @WebMethod
    @ResponseWrapper(localName = "verifyPropertyResponse", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.VerifyPropertyResponse")
    public eu.aniketos.ncvm.client.IVerificationResult verifyProperty(
        @WebParam(name = "arg0", targetNamespace = "http://ncvm.aniketos.eu/")
        eu.aniketos.ncvm.client.ICompositionPlan arg0,
        @WebParam(name = "arg1", targetNamespace = "http://ncvm.aniketos.eu/")
        eu.aniketos.ncvm.client.IConsumerPolicy arg1
    );

    @RequestWrapper(localName = "configureNCVMFeedback", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.ConfigureNCVMFeedback")
    @WebMethod
    @ResponseWrapper(localName = "configureNCVMFeedbackResponse", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.ConfigureNCVMFeedbackResponse")
    public void configureNCVMFeedback(
        @WebParam(name = "arg0", targetNamespace = "http://ncvm.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://ncvm.aniketos.eu/")
        boolean arg1
    );

    @WebResult(name = "return", targetNamespace = "http://ncvm.aniketos.eu/")
    @RequestWrapper(localName = "verifyPropertyDeployed", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.VerifyPropertyDeployed")
    @WebMethod
    @ResponseWrapper(localName = "verifyPropertyDeployedResponse", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.VerifyPropertyDeployedResponse")
    public eu.aniketos.ncvm.client.IVerificationResult verifyPropertyDeployed(
        @WebParam(name = "arg0", targetNamespace = "http://ncvm.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://ncvm.aniketos.eu/")
        eu.aniketos.ncvm.client.IConsumerPolicy arg1
    );

    @RequestWrapper(localName = "configureCSVM", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.ConfigureCSVM")
    @WebMethod
    @ResponseWrapper(localName = "configureCSVMResponse", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.ConfigureCSVMResponse")
    public void configureCSVM(
        @WebParam(name = "arg0", targetNamespace = "http://ncvm.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://ncvm.aniketos.eu/")
        boolean arg1
    );

    @RequestWrapper(localName = "configureMarketplace", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.ConfigureMarketplace")
    @WebMethod
    @ResponseWrapper(localName = "configureMarketplaceResponse", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.ConfigureMarketplaceResponse")
    public void configureMarketplace(
        @WebParam(name = "arg0", targetNamespace = "http://ncvm.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://ncvm.aniketos.eu/")
        boolean arg1
    );

    @RequestWrapper(localName = "configurePVM", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.ConfigurePVM")
    @WebMethod
    @ResponseWrapper(localName = "configurePVMResponse", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.ConfigurePVMResponse")
    public void configurePVM(
        @WebParam(name = "arg0", targetNamespace = "http://ncvm.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://ncvm.aniketos.eu/")
        boolean arg1
    );

    @RequestWrapper(localName = "configureSPDM", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.ConfigureSPDM")
    @WebMethod
    @ResponseWrapper(localName = "configureSPDMResponse", targetNamespace = "http://ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.client.ConfigureSPDMResponse")
    public void configureSPDM(
        @WebParam(name = "arg0", targetNamespace = "http://ncvm.aniketos.eu/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://ncvm.aniketos.eu/")
        boolean arg1
    );
}
