package eu.aniketos.ncvm.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2014-02-27T00:54:55.063Z
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "INestedCompositionVerification", 
                  wsdlLocation = "http://ec2-54-235-118-152.compute-1.amazonaws.com:9093/ncvm?wsdl",
                  targetNamespace = "http://ncvm.aniketos.eu/") 
public class INestedCompositionVerificationClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ncvm.aniketos.eu/", "INestedCompositionVerification");
    public final static QName INestedCompositionVerificationPort = new QName("http://ncvm.aniketos.eu/", "INestedCompositionVerificationPort");
    static {
        URL url = null;
        try {
            url = new URL("http://ec2-54-235-118-152.compute-1.amazonaws.com:9093/ncvm?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(INestedCompositionVerificationClient.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ec2-54-235-118-152.compute-1.amazonaws.com:9093/ncvm?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public INestedCompositionVerificationClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public INestedCompositionVerificationClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public INestedCompositionVerificationClient() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns INestedCompositionVerificationPortType
     */
    @WebEndpoint(name = "INestedCompositionVerificationPort")
    public INestedCompositionVerificationPortType getINestedCompositionVerificationPort() {
        return super.getPort(INestedCompositionVerificationPort, INestedCompositionVerificationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns INestedCompositionVerificationPortType
     */
    @WebEndpoint(name = "INestedCompositionVerificationPort")
    public INestedCompositionVerificationPortType getINestedCompositionVerificationPort(WebServiceFeature... features) {
        return super.getPort(INestedCompositionVerificationPort, INestedCompositionVerificationPortType.class, features);
    }

}
