package eu.aniketos.ncvm.userinterface.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-28T00:14:59.624+01:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "INCVMFeedback", 
                  wsdlLocation = "http://montefalco:9094/ncvmfeedback?wsdl",
                  targetNamespace = "http://userinterface.ncvm.aniketos.eu/") 
public class INCVMFeedbackClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://userinterface.ncvm.aniketos.eu/", "INCVMFeedback");
    public final static QName INCVMFeedbackPort = new QName("http://userinterface.ncvm.aniketos.eu/", "INCVMFeedbackPort");
    static {
        URL url = null;
        try {
            url = new URL("http://montefalco:9094/ncvmfeedback?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(INCVMFeedbackClient.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://montefalco:9094/ncvmfeedback?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public INCVMFeedbackClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public INCVMFeedbackClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public INCVMFeedbackClient() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns INCVMFeedbackPortType
     */
    @WebEndpoint(name = "INCVMFeedbackPort")
    public INCVMFeedbackPortType getINCVMFeedbackPort() {
        return super.getPort(INCVMFeedbackPort, INCVMFeedbackPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns INCVMFeedbackPortType
     */
    @WebEndpoint(name = "INCVMFeedbackPort")
    public INCVMFeedbackPortType getINCVMFeedbackPort(WebServiceFeature... features) {
        return super.getPort(INCVMFeedbackPort, INCVMFeedbackPortType.class, features);
    }

}
