
package eu.aniketos.ncvm.userinterface.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-28T00:14:59.500+01:00
 * Generated source version: 2.7.4
 * 
 */
public final class INCVMFeedbackPortType_INCVMFeedbackPort_Client {

    private static final QName SERVICE_NAME = new QName("http://userinterface.ncvm.aniketos.eu/", "INCVMFeedback");

    private INCVMFeedbackPortType_INCVMFeedbackPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = INCVMFeedbackClient.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        INCVMFeedbackClient ss = new INCVMFeedbackClient(wsdlURL, SERVICE_NAME);
        INCVMFeedbackPortType port = ss.getINCVMFeedbackPort();  
        
        {
        System.out.println("Invoking logLine...");
        java.lang.String _logLine_arg0 = "";
        port.logLine(_logLine_arg0);


        }

        System.exit(0);
    }

}
