package eu.aniketos.ncvm.userinterface.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-28T00:14:59.595+01:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://userinterface.ncvm.aniketos.eu/", name = "INCVMFeedbackPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface INCVMFeedbackPortType {

    @RequestWrapper(localName = "logLine", targetNamespace = "http://userinterface.ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.userinterface.client.LogLine")
    @WebMethod
    @ResponseWrapper(localName = "logLineResponse", targetNamespace = "http://userinterface.ncvm.aniketos.eu/", className = "eu.aniketos.ncvm.userinterface.client.LogLineResponse")
    public void logLine(
        @WebParam(name = "arg0", targetNamespace = "http://userinterface.ncvm.aniketos.eu/")
        java.lang.String arg0
    );
}
