
package eu.avantssar.satmc;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SATMCService", targetNamespace = "http://avantssar.eu/satmc/", wsdlLocation = "http://satmc.ai.dist.unige.it/avantssar/service/satmc/?wsdl")
public class SATMCService
    extends Service
{

    private final static URL SATMCSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(eu.avantssar.satmc.SATMCService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = eu.avantssar.satmc.SATMCService.class.getResource(".");
            url = new URL(baseUrl, "http://satmc.ai.dist.unige.it/avantssar/service/satmc/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://satmc.ai.dist.unige.it/avantssar/service/satmc/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SATMCSERVICE_WSDL_LOCATION = url;
    }

    public SATMCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SATMCService() {
        super(SATMCSERVICE_WSDL_LOCATION, new QName("http://avantssar.eu/satmc/", "SATMCService"));
    }

    /**
     * 
     * @return
     *     returns SATMCPortType
     */
    @WebEndpoint(name = "SATMCSOAPPort")
    public SATMCPortType getSATMCSOAPPort() {
        return super.getPort(new QName("http://avantssar.eu/satmc/", "SATMCSOAPPort"), SATMCPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SATMCPortType
     */
    @WebEndpoint(name = "SATMCSOAPPort")
    public SATMCPortType getSATMCSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://avantssar.eu/satmc/", "SATMCSOAPPort"), SATMCPortType.class, features);
    }

}
